# Generated by Django 4.0.4 on 2022-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=63)),
                ('real_name', models.CharField(max_length=63)),
                ('real_surname', models.CharField(max_length=63)),
                ('nationality', models.CharField(max_length=31)),
                ('team', models.CharField(max_length=31)),
                ('region', models.CharField(max_length=31)),
            ],
            options={
                'verbose_name_plural': 'players',
            },
        ),
    ]
