# Generated by Django 4.0.4 on 2022-05-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next_match_date',
            field=models.CharField(default='Unknown', max_length=31),
        ),
        migrations.AddField(
            model_name='player',
            name='next_match_url',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
