# Generated by Django 4.0.4 on 2022-05-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0002_player_next_match_date_player_next_match_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='next_match_date',
            field=models.CharField(default='Неизвестно', max_length=31),
        ),
        migrations.AlterField(
            model_name='player',
            name='next_match_url',
            field=models.CharField(default='Неизвестно', max_length=255),
        ),
    ]
